-- MySQL Script generated by MySQL Workbench
-- Sun May  7 20:47:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bddcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bddcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bddcc` DEFAULT CHARACTER SET utf8mb4 ;
USE `bddcc` ;

-- -----------------------------------------------------
-- Table `bddcc`.`matieres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddcc`.`matieres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bddcc`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddcc`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin` INT NOT NULL,
  `nom` TEXT NOT NULL,
  `prenom` TEXT NOT NULL,
  `pseudo` TEXT NOT NULL,
  `sexe` TEXT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `email` TEXT NOT NULL,
  `mdp` TEXT NOT NULL,
  `bio` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bddcc`.`annonces_aides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddcc`.`annonces_aides` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `theme` INT NULL DEFAULT NULL,
  `auteur_aide` INT NOT NULL,
  `description` TEXT NOT NULL,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `theme_idx` (`theme` ASC),
  INDEX `auteur_idx` (`auteur_aide` ASC),
  CONSTRAINT `theme`
    FOREIGN KEY (`theme`)
    REFERENCES `bddcc`.`matieres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `auteur_aide`
    FOREIGN KEY (`auteur_aide`)
    REFERENCES `bddcc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bddcc`.`annonces_aides_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddcc`.`annonces_aides_likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `annonce_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `annonce_id_idx` (`annonce_id` ASC),
  CONSTRAINT `user_id_aides_likes`
    FOREIGN KEY (`user_id`)
    REFERENCES `bddcc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `annonce_id`
    FOREIGN KEY (`annonce_id`)
    REFERENCES `bddcc`.`annonces_aides` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bddcc`.`annonces_promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddcc`.`annonces_promotions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auteur_promotion` INT NOT NULL,
  `titre` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  `filtre` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `auteur_idx` (`auteur_promotion` ASC),
  CONSTRAINT `auteur_promotion`
    FOREIGN KEY (`auteur_promotion`)
    REFERENCES `bddcc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bddcc`.`message_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddcc`.`message_admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auteur` INT NOT NULL,
  `message` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `auteur_idx` (`auteur` ASC),
  CONSTRAINT `auteur`
    FOREIGN KEY (`auteur`)
    REFERENCES `bddcc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bddcc`.`message_prives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddcc`.`message_prives` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `expediteur` INT NOT NULL,
  `destinataire` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `message` TEXT NOT NULL,
PRIMARY KEY (`id`),
INDEX `expediteur_idx` (`expediteur` ASC, `destinataire` ASC),
CONSTRAINT `expediteur`
  FOREIGN KEY (`expediteur`)
  REFERENCES `bddcc`.`users` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
CONSTRAINT `destinataire`
  FOREIGN KEY (`destinataire`)
  REFERENCES `bddcc`.`users` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bddcc`.`profil_commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddcc`.`profil_commentaires` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `commentateur` INT NOT NULL,
  `message` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC, `commentateur` ASC),
  CONSTRAINT `user_id_profil_commentaires`
    FOREIGN KEY (`user_id`)
    REFERENCES `bddcc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `commentateur`
    FOREIGN KEY (`commentateur`)
    REFERENCES `bddcc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
